Add new Ruby versions 2.5.3 and 2.4.5
Also edit README to emphasise issues with older Ruby versions (and therefore base images built on them), and still trying to get the build process working better.

diff --git a/Dockerfile.no-qt.alpine b/Dockerfile.no-qt.alpine
--- a/Dockerfile.no-qt.alpine
+++ b/Dockerfile.no-qt.alpine
@@ -20,3 +20,12 @@ LABEL version="${VERSION}"
 RUN apk add --no-cache alpine-sdk bash build-base libressl-dev nodejs tzdata zsh
 RUN gem install yard && yard config --gem-install-yri \
     && gem install bundler && gem update --system && gem update && gem cleanup
+# This will fail to uninstall `did_you_mean` on 2.4.x Rubies, which is what we
+# want since it was never *installed* on 2.4.x Rubies. ;-)
+RUN gem uninstall -i /usr/local/lib/ruby/gems/2.5.0 did_you_mean || true
+RUN gem uninstall -i /usr/local/lib/ruby/gems/$RUBY_MAJOR.0 minitest && \
+    gem uninstall -i /usr/local/lib/ruby/gems/$RUBY_MAJOR.0 net-telnet && \
+    gem uninstall -i /usr/local/lib/ruby/gems/$RUBY_MAJOR.0 power_assert && \
+    gem uninstall -i /usr/local/lib/ruby/gems/$RUBY_MAJOR.0 rake && \
+    gem uninstall -i /usr/local/lib/ruby/gems/$RUBY_MAJOR.0 test-unit && \
+    gem cleanup
diff --git a/Dockerfile.no-qt.debian b/Dockerfile.no-qt.debian
--- a/Dockerfile.no-qt.debian
+++ b/Dockerfile.no-qt.debian
@@ -16,9 +16,19 @@ LABEL maintainer="Jeff Dickey <jdickey at seven-sigma dot com>"
 LABEL description="Base image for ${RUBY_VERSION}${RUBY_EXTRA}, with NodeJS, but without Qt"
 LABEL includesQt=false
 LABEL version="${VERSION}"
+LABEL jdickey_ruby_no-qt_image_version="${VERSION}"
 
 RUN apt-get update -qq && apt-get dist-upgrade -y && \
     apt-get install -y build-essential curl less nodejs sudo wget zsh \
     && apt-get clean && find /var/lib/apt/lists/* -delete
 RUN gem install yard && yard config --gem-install-yri \
     && gem install bundler && gem update --system && gem update && gem cleanup
+# This will fail to uninstall `did_you_mean` on 2.4.x Rubies, which is what we
+# want since it was never *installed* on 2.4.x Rubies. ;-)
+RUN gem uninstall -i /usr/local/lib/ruby/gems/2.5.0 did_you_mean || true
+RUN gem uninstall -i /usr/local/lib/ruby/gems/$RUBY_MAJOR.0 minitest && \
+    gem uninstall -i /usr/local/lib/ruby/gems/$RUBY_MAJOR.0 net-telnet && \
+    gem uninstall -i /usr/local/lib/ruby/gems/$RUBY_MAJOR.0 power_assert && \
+    gem uninstall -i /usr/local/lib/ruby/gems/$RUBY_MAJOR.0 rake && \
+    gem uninstall -i /usr/local/lib/ruby/gems/$RUBY_MAJOR.0 test-unit && \
+    gem cleanup
